feat: add properties
Djaytan/mc-jobs-reborn-patch-place-break pull request #107
Opened 2023-02-24 09:06 UTC by jeanbaptisterevel

2023-02-24 09:33 UTC, Djaytan requested changes
C'est une bonne première étape de faite ! Tu as réussi à rentrer dans le code et à apporter ta première contribution, félicitations ! :)

Maintenant, on va ajuster ce que tu as fais pour vraiment avoir quelque chose de clean avant de merger (c.f. mes commentaires)

Anyway bon boulot ^^

2023-02-24 09:33 UTC, Djaytan commented on src/patch-place-break/patch-place-break-api/src/main/java/fr/djaytan/minecraft/jobsreborn/patchplacebreak/api/properties/RestrictedBlocksProperties.java
> +  private final List<String> materials = new ArrayList<>();
La collection de materials ne doit pas contenir de doublons
-> Set
Pour l'implémentation vu que l'ordre n'a aucune importance : HashSet

2023-02-24 09:33 UTC, Djaytan commented on src/patch-place-break/patch-place-break-api/src/main/java/fr/djaytan/minecraft/jobsreborn/patchplacebreak/api/properties/RestrictedBlocksProperties.java
> +  public void addMaterial(String materialName) {
Les méthodes addMaterial, clear et cie ne servent à rien et font même pire que ça
La raison est simple : la classe doit être immutable. Je ne l'ai pas exprimé, mais effectivement il ne faut pas avoir la possibilité de modifier l'état de l'objet une fois celui-ci créé

2023-02-24 09:33 UTC, Djaytan commented on src/patch-place-break/patch-place-break-api/src/main/java/fr/djaytan/minecraft/jobsreborn/patchplacebreak/api/properties/RestrictedBlocksProperties.java
> +  public void addMaterial(String materialName) {
L'annotation de Lombok `@Value` permet de générer une classe immutable
Je te recommande de consulter les autres classes de propriétés :
1 - Pour comprendre comment c'est fait
2 - Pour être consistant avec le reste du code

L'annotation Value typiquement te génère les constructors, les getters, equals(), hashCode() et toString() et te mets les fields en private sans que tu aies à l'expliciter

Donc tu peux également supprimer les constructors et les getters... Sauf si tu es mesure de justifier pourquoi il faut réécrire le constructor de Lombok dans ce cas de figure précis (indice : c'est en lien avec une limitation de Lombok dans la génération des classes immutables)
Si tu ne vois pas, alors pour l'instant applique simplement l'annotation `@Value`
Tu es censé n'avoir que deux fields définis, et c'est tout

2023-02-24 09:36 UTC, Djaytan commented on src/patch-place-break/patch-place-break-api/src/main/java/fr/djaytan/minecraft/jobsreborn/patchplacebreak/api/properties/RestrictedBlocksProperties.java
> +  private final List<String> materials = new ArrayList<>();
HashSet offre de meilleurs performances et comparaison d'un SortedSet par exemple
Mais en réalité le gain de performances ici est clairement négligeable par rapport au coût de lecture en base de données en mode bloquant
HashSet c'est aussi l'implémentation pas défaut d'un Set aussi j'ai envie de dire, du moins je mets toujours ça par défaut quand je n'ai pas de besoins spécifiques
L'équivalent du ArrayList pour une List, ou d'une HashMap pour une Map

2023-02-26 14:24 UTC, jeanbaptisterevel commented on src/patch-place-break/patch-place-break-api/src/main/java/fr/djaytan/minecraft/jobsreborn/patchplacebreak/api/properties/RestrictedBlocksProperties.java
> +  public void addMaterial(String materialName) {
Les méthodes addMaterial, clear et cie je pensais les implémenter pour permettre une configuration en jeu, par habitude 

Je sais que beaucoup demandent qu'il y ait de la configuration disponible en jeu et c'est pour ça que j'essaye de maximiser cet aspect dans mes plugins

2023-02-26 14:44 UTC, jeanbaptisterevel commented on src/patch-place-break/patch-place-break-api/src/main/java/fr/djaytan/minecraft/jobsreborn/patchplacebreak/api/properties/RestrictedBlocksProperties.java
> +  public void addMaterial(String materialName) {
Pour ce qui est de réécrire le constructor de Lombok, d'après les recherches que j'ai pu faire, j'imagine que c'est car Lombok ne permet pas la validation des données lors de l'instanciation de l'objet. Par exemple, on peut simplement demander à ce que nos propriétés ne soient pas null avec l'annotation `@NonNull`, mais je pense qu'il ne sera pas possible de vérifier que chaque String données dans le HashSet seront bien des materials. 
Maintenant, je me demande si cette vérification est de la responsabilité de la classe `RestrictedBlocksProperties`, car on pourrait très bien donner cette responsabilité à la classe qui sera chargée de charger nos données depuis le fichier de config ?

2023-02-26 14:44 UTC, jeanbaptisterevel commented on src/patch-place-break/patch-place-break-api/src/main/java/fr/djaytan/minecraft/jobsreborn/patchplacebreak/api/properties/RestrictedBlocksProperties.java
> +public class RestrictedBlocksProperties {
Oupsi 😅

2023-02-26 19:02 UTC, Djaytan commented on src/patch-place-break/patch-place-break-api/src/main/java/fr/djaytan/minecraft/jobsreborn/patchplacebreak/api/properties/RestrictedBlocksProperties.java
> +  public void addMaterial(String materialName) {
@jeanbaptisterevel 
Concernant la possibilité d'éditer la configuration du plugin à chaud, c'est le sujet de cette issue: https://github.com/Djaytan/mc-jobs-reborn-patch-place-break/issues/48
Le seul moyen acceptable de reload les configs, ça sera en désactivant et en réactivant le plugin. Les choses ont été conçues ainsi.
La raison principale est la volontée de bannir les classes mutables en raison des coûts supplémentaires et les risques de dégradation du code liés à leur usage, en particulier lorsque l'on rentre dans un contexte de programmation concurrente... Et c'est notre cas ici ce qui veut dire que ton travail actuel est insuffisant pour rendre la classe mutable utilisable de façon safe. Pour plus d'infos: https://stackoverflow.com/a/3769639
En bref: virer ces méthodes qui empêchent la classe d'être immutable, et rendre la classe immutable.

Pour la question de Lombok, ce n'est pas lié à la validation des données. Si tu annote les fields avec `@NonNull`, les paramètres du constructeur auront également ces annotations appliquées. Par contre, ce que Lombok ne fait pas alors que c'est indispensable pour rendre la classe immutable, c'est de rendre la collection immutable également. Typiquement, un appel à `Collections.immutableSet()` ou quelque chose du genre. Et puisque le contenu de la collection c'est des `String`s, classe immutable, alors on a pas besoin de se casser la tête plus que ça.

2023-02-26 19:39 UTC, Djaytan requested changes

2023-02-26 19:39 UTC, Djaytan commented on src/patch-place-break/patch-place-break-api/src/test/java/fr/djaytan/minecraft/jobsreborn/patchplacebreak/api/properties/RestrictedBlocksPropertiesTest.java
> +        () -> assertThat(restrictedBlocksProperties.getMaterials()).isEqualTo(materials),
Immutability: KO

2023-02-26 19:40 UTC, Djaytan requested changes

2023-02-26 19:40 UTC, Djaytan commented on src/patch-place-break/patch-place-break-api/src/main/java/fr/djaytan/minecraft/jobsreborn/patchplacebreak/api/properties/RestrictedBlocksProperties.java
> +  public boolean isRestricted(String material) {
YAGNI
Donc retire là :)
Si on en a besoin plus tard, alors on pourra éventuellement considérer la rajouter

2023-02-26 19:50 UTC, jeanbaptisterevel commented on src/patch-place-break/patch-place-break-api/src/test/java/fr/djaytan/minecraft/jobsreborn/patchplacebreak/api/properties/RestrictedBlocksPropertiesTest.java
> +        () -> assertThat(restrictedBlocksProperties.getMaterials()).isEqualTo(materials),
En quoi cela influe sur l'immutabilité ?

2023-02-26 19:51 UTC, jeanbaptisterevel commented on src/patch-place-break/patch-place-break-api/src/main/java/fr/djaytan/minecraft/jobsreborn/patchplacebreak/api/properties/RestrictedBlocksProperties.java
> +  public boolean isRestricted(String material) {
Je pensais l'utiliser pour vérifier si le material du block était restreint pendant un event... C'est mauvais ?

2023-02-26 19:57 UTC, Djaytan commented on src/patch-place-break/patch-place-break-api/src/main/java/fr/djaytan/minecraft/jobsreborn/patchplacebreak/api/properties/RestrictedBlocksProperties.java
> +  public boolean isRestricted(String material) {
C'est une question qu'on se posera au moment de cette partie là de l'implémentation.

Btw l'implémentation est incorrecte aussi ^^ (implémentation valide si le mode est `BLACKLIST`, invalide si `WHITELIST` + le nom est mal choisi -> `isExcluded` me parait meilleur)

Si tu veux vraiment implémenter la méthode et que tu es certain qu'elle te seras utile pour l'implémentation, alors test là alors avec plusieurs tests unitaires (actuellement il n'y en a aucun pour la méthode)

2023-02-26 20:00 UTC, Djaytan commented on src/patch-place-break/patch-place-break-api/src/test/java/fr/djaytan/minecraft/jobsreborn/patchplacebreak/api/properties/RestrictedBlocksPropertiesTest.java
> +        () -> assertThat(restrictedBlocksProperties.getMaterials()).isEqualTo(materials),
```java
  @Test
  @DisplayName("Constructor - Successful nominal case")
  void shouldSuccessWhenCreatingWithNominalValues() {
    // Given
    Set<String> materials = new HashSet<>(Arrays.asList("COBBLESTONE", "STONE", "DIAMOND_BLOCK"));
    RestrictionMode mode = RestrictionMode.WHITELIST;

    // When
    RestrictedBlocksProperties restrictedBlocksProperties =
        RestrictedBlocksProperties.of(materials, mode);

    materials.add("GLASS"); // OOPS! Immutability broken

    // Then
    assertAll(
        "Verification of returned values from getters",
        () -> assertThat(restrictedBlocksProperties.getMaterials()).isEqualTo(new HashSet<(Arrays.asList("COBBLESTONE", "STONE", "DIAMOND_BLOCK"))), // Fail here
        () -> assertThat(restrictedBlocksProperties.getMode()).isEqualTo(mode));
  }
```

2023-02-28 23:36 UTC, Djaytan requested changes

2023-02-28 23:36 UTC, Djaytan commented on src/patch-place-break/patch-place-break-api/src/main/java/fr/djaytan/minecraft/jobsreborn/patchplacebreak/api/properties/RestrictedBlocksProperties.java
> +public class RestrictedBlocksProperties {
Javadoc to add

2023-02-28 23:36 UTC, Djaytan commented on src/patch-place-break/patch-place-break-api/src/main/java/fr/djaytan/minecraft/jobsreborn/patchplacebreak/api/properties/RestrictionMode.java
> +public enum RestrictionMode {
Javadoc to add

2023-03-03 19:02 UTC, Djaytan approved these changes

2023-03-03 19:53 UTC, merged